version: "3.8"
services:
    app:
        environment:
            - PROJECT_ID=mike-test-cmdb-gke
            - SECRET_ID=foo
            - SECRET_VERSION_ID=latest
            - PORT="3000"
        build:
            context: ./app
        ports:
            - "3000:3000"
    proxy:
        restart: always
        build:
            context: ./app-proxy
        ports:
            - "80:8080"