# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: app-sa@mike-test-cmdb-gke.iam.gserviceaccount.com
  name: app-sa
  namespace: app-ns